### ISSUE TITLE
How should i go about adding an api url for the lastfm plugin?

### ISSUE THREAD

**Issue by k-e-l-p** [FrozenPigs/Taigabot3#2]
should i have it in config.json or should i just keep it in the plugin itself?
if i place it in config.json, should i have it like this?
`{
  "db_dir": "./persist/db/",
  "log_dir": "./persist/logs/",
  "valid_command_prefixes": [
    ".",
    ",",
    "$",
    "!",
    "&",
    "+",
    "-"
  ],
  "api_keys": {
    "last_fm": "key"
   },
  "api_urls":{
      "last_fm": "https://api.lastfm.com"
  }`
or like this?
`{
  "db_dir": "./persist/db/",
  "log_dir": "./persist/logs/",
  "valid_command_prefixes": [
    ".",
    ",",
    "$",
    "!",
    "&",
    "+",
    "-"
  ],
  "api_keys": {
    "last_fm": {
        "key": "api-key",
        "api_url": "https://api.lastfm.com"
    }
   },
 `
the reason why i dont want to specify the url in the request calls is because libre.fm is api-compatible with last.fm, and therefore fully interchangeable within the bot.

**Comment by k-e-l-p** [comment]
for now, i'm going to specify the api url as a global variable in the plugin itself, which would make it easy to modify in the future.

**Comment by FrozenPigs** [comment]
Yea do "api_keys": { "last_fm": "key" }.

**Comment by k-e-l-p** [comment]
not the actual key itself, but the link to the API, since there are a bunch of other API compatible sites such as libre.fm

**Comment by FrozenPigs** [comment]
I know that, but taiga usus just lastfm, and unless you wanted to let users config which one to use I'd just leave it as is.

**Comment by k-e-l-p** [comment]
Alright, please check the pull request.
